// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogHeader: typeof import('./components/page-sections/blog/blog-header/BlogHeader.vue')['default']
    BlogPosts: typeof import('./components/page-sections/blog/blog-posts/BlogPosts.vue')['default']
    FormularioDeOportunidad: typeof import('./components/single-items/FormularioDeOportunidad.vue')['default']
    InicioAliados: typeof import('./components/page-sections/inicio/inicio-aliados/inicioAliados.vue')['default']
    InicioCTA: typeof import('./components/page-sections/inicio/inicio-cta/InicioCTA.vue')['default']
    InicioExpo: typeof import('./components/page-sections/inicio/inicio-expo/InicioExpo.vue')['default']
    InicioHero: typeof import('./components/page-sections/inicio/inicio-hero/InicioHero.vue')['default']
    InicioTestimonios: typeof import('./components/page-sections/inicio/inicio-testimonios/InicioTestimonios.vue')['default']
    InversionesHeader: typeof import('./components/page-sections/inversiones/inversiones-header/InversionesHeader.vue')['default']
    ListaOportunidades: typeof import('./components/lists/ListaOportunidades.vue')['default']
    LoadingSpinner: typeof import('./components/general/loader/LoadingSpinner.vue')['default']
    Modal: typeof import('./components/general/site-modal/Modal.vue')['default']
    NavBar: typeof import('./components/general/site-navbar/NavBar.vue')['default']
    NavMenu: typeof import('./components/general/site-menu/NavMenu.vue')['default']
    NosotrosAliados: typeof import('./components/page-sections/nosotros/nosotros-aliados/NosotrosAliados.vue')['default']
    NosotrosCta: typeof import('./components/page-sections/nosotros/nosotros-cta/NosotrosCta.vue')['default']
    NosotrosEquipo: typeof import('./components/page-sections/nosotros/nosotros-equipo/NosotrosEquipo.vue')['default']
    NosotrosHeader: typeof import('./components/page-sections/nosotros/nosotros-header/NosotrosHeader.vue')['default']
    NosotrosValores: typeof import('./components/page-sections/nosotros/nosotros-valores/NosotrosValores.vue')['default']
    Oportunidad: typeof import('./components/single-items/Oportunidad.vue')['default']
    PageSection: typeof import('./components/page-sections/shared/PageSection.vue')['default']
    PrestamosCalculadora: typeof import('./components/page-sections/prestamos/prestamos-calculadora/PrestamosCalculadora.vue')['default']
    PrestamosHeader: typeof import('./components/page-sections/prestamos/prestamos-header/PrestamosHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareTest: typeof import('./components/page-sections/shared/ShareTest.vue')['default']
    SiteFooter: typeof import('./components/general/site-footer/SiteFooter.vue')['default']
    TransparenciaHeader: typeof import('./components/page-sections/transparencia/transparencia-header/TransparenciaHeader.vue')['default']
    TransparenciaLinks: typeof import('./components/page-sections/transparencia/transparencia-links/TransparenciaLinks.vue')['default']
  }
}

export {}
